# DCS-404 Lab-1 work
**Name:** Safola Bhattarai 


---
## 3.1 Exercise on Functions

## Task-1: Unit Conversion Program

In [5]:
def convert_units(choice, value):
    if choice == 1:
        return value * 3.28084, "Meters to Feet", "ft"
    elif choice == 2:
        return value / 3.28084, "Feet to Meters", "m"
    elif choice == 3:
        return value * 2.20462, "Kilograms to Pounds", "lbs"
    elif choice == 4:
        return value / 2.20462, "Pounds to Kilograms", "kg"
    elif choice == 5:
        return value * 0.264172, "Liters to Gallons", "gal"
    elif choice == 6:
        return value / 0.264172, "Gallons to Liters", "L"
    else:
        return None, None, None


print("Unit Converter")
print("1. Meters to Feet")
print("2. Feet to Meters")
print("3. Kilograms to Pounds")
print("4. Pounds to Kilograms")
print("5. Liters to Gallons")
print("6. Gallons to Liters")

try:
    choice = int(input("Enter your choice (1-6): "))
    value = float(input("Enter the value to convert: "))

    result, conversion_name, unit = convert_units(choice, value)

    if result is not None:
        print(conversion_name + " = " + str(round(result, 2)) + " " + unit)
    else:
        print("Invalid conversion choice.")

except ValueError:
    print("Error: Please enter numeric values only.")

Unit Converter
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Kilograms to Pounds = 6.61 lbs


### Task-2: Math Operations on a List of Numbers

In [8]:

def find_sum(numbers):
    return sum(numbers)
def find_average(numbers):
    return sum(numbers) / len(numbers)
def find_maximum(numbers):
    return max(numbers)
def find_minimum(numbers):
    return min(numbers)

print("Mathematical Operations Program")
print("1. Find Sum")
print("2. Find Average")
print("3. Find Maximum")
print("4. Find Minimum")
try:
    choice = int(input("Enter your choice (1-4): "))
    user_input = input("Enter numbers separated by spaces: ")
    numbers = [float(num) for num in user_input.split()]

    if len(numbers) == 0:
        print("Error: List is empty.")
    else:
        if choice == 1:
            print("Sum =", find_sum(numbers))

        elif choice == 2:
            print("Average =", find_average(numbers))

        elif choice == 3:
            print("Maximum =", find_maximum(numbers))

        elif choice == 4:
            print("Minimum =", find_minimum(numbers))

        else:
            print("Invalid choice.")
except ValueError:
    print("Error: Please enter valid numeric values.")

Mathematical Operations Program
1. Find Sum
2. Find Average
3. Find Maximum
4. Find Minimum
Maximum = 4.0


---
## 3.2 Exercise on List Manipulation

#### Extract Every Other Element, slice a sublist, reverse a list using slicing, remove the first and last elements, get the first n elements, extract eleemnts from the end, extract elements in reverse order

In [9]:
# Extract every other element
def extract_every_other(lst):
    return lst[::2]

# Return sublist from indexes
def get_sublist(lst, start, end):
    return lst[start:end+1]

# Reverse list using slicing
def reverse_list(lst):
    return lst[::-1]

# Remove first and last
def remove_first_last(lst):
    return lst[1:-1]

# Get first n elements
def get_first_n(lst, n):
    return lst[:n]

# Get last n elements
def get_last_n(lst, n):
    return lst[-n:]

# Reverse skipping one element
def reverse_skip(lst):
    return lst[-2::-2]

# Example list
numbers = [1, 2, 3, 4, 5, 6]
print("Original List:", numbers)
print("Every Other Element:", extract_every_other(numbers))
print("Sublist (2 to 4):", get_sublist(numbers, 2, 4))
print("Reversed List:", reverse_list(numbers))
print("Without First and Last:", remove_first_last(numbers))
print("First 3 Elements:", get_first_n(numbers, 3))
print("Last 2 Elements:", get_last_n(numbers, 2))
print("Reverse Skip List:", reverse_skip(numbers))

Original List: [1, 2, 3, 4, 5, 6]
Every Other Element: [1, 3, 5]
Sublist (2 to 4): [3, 4, 5]
Reversed List: [6, 5, 4, 3, 2, 1]
Without First and Last: [2, 3, 4, 5]
First 3 Elements: [1, 2, 3]
Last 2 Elements: [5, 6]
Reverse Skip List: [5, 3, 1]


---
## 3.3 Exercise on Nested Lists

#### 1. Flatten a Nested List

In [10]:
def flatten(lst):
    result = []

    for item in lst:
        for value in item:
            result.append(value)

    return result


print(flatten([[1, 2], [3, 4], [5]]))

[1, 2, 3, 4, 5]


#### 2. Accessing Nested List Elements

In [11]:
def access_nested_element(lst, indices):
    return lst[indices[0]][indices[1]]


lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

print(access_nested_element(lst, indices))

6


#### 3. Sum of All Elements in a Nested List

In [12]:
def sum_nested(lst):
    total = 0

    for item in lst:
        if type(item) == list:
            total += sum_nested(item)
        else:
            total += item

    return total


print(sum_nested([[1, 2], [3, [4, 5]], 6]))

21


#### 4. Remove Specific Element from a Nested List

In [13]:
def remove_element(lst, elem):
    result = []

    for item in lst:
        new_list = []

        for value in item:
            if value != elem:
                new_list.append(value)

        result.append(new_list)

    return result


lst = [[1, 2], [3, 2], [4, 5]]

print(remove_element(lst, 2))

[[1], [3], [4, 5]]


#### 5. Find the Maximum Element in a Nested List

In [14]:
def find_max(lst):
    biggest = 0

    for item in lst:
        if type(item) == list:
            value = find_max(item)

            if value > biggest:
                biggest = value

        else:
            if item > biggest:
                biggest = item

    return biggest


print(find_max([[1, 2], [3, [4, 5]], 6]))

6


#### 6. Count Occurrences of an Element in a Nested List

In [15]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        for value in item:
            if value == elem:
                count += 1

    return count


lst = [[1, 2], [2, 3], [2, 4]]

print(count_occurrences(lst, 2))

3


#### 7. Deep Flatten (Any Depth)

In [16]:
def deep_flatten(lst):
    result = []

    for item in lst:
        if type(item) == list:
            result += deep_flatten(item)
        else:
            result.append(item)

    return result


lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

print(deep_flatten(lst))

[1, 2, 3, 4, 5, 6, 7, 8]


#### 8. Nested List Average

In [17]:
def average_nested(lst):
    total = 0
    count = 0

    for item in lst:
        for value in item:
            total += value
            count += 1

    return total / count


print(average_nested([[1, 2], [3, 4], [5, 6]]))

3.5


## Numpy SAFOLA BHATTARAI WEEK 2 ASSIGNMENT

#### 9.1 Basic vector and matrix operation with numpy

#### Problem 1 array creation 

In [18]:
import numpy as np

# 1. Empty array 2x2
a = np.empty((2, 2))
print(a)

# 2. Ones array 4x2
b = np.ones((4, 2))
print(b)

# 3. Full array
c = np.full((2, 2), 7)
print(c)

# 4. Zeros like array
d = np.zeros_like(c)
print(d)

# 5. Ones like array
e = np.ones_like(c)
print(e)

# 6. List to numpy array
new_list = [1, 2, 3, 4]

f = np.array(new_list)
print(f)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[0 0]
 [0 0]]
[[1 1]
 [1 1]]
[1 2 3 4]


#### Problem 2 Array manipulation

In [19]:
import numpy as np

# 1. Array from 10 to 49
a = np.arange(10, 50)
print(a)

# 2. 3x3 matrix from 0 to 8
b = np.arange(9).reshape(3, 3)
print(b)

# 3. Identity matrix
c = np.eye(3)
print(c)

# 4. Random array of size 30 and mean
d = np.random.random(30)
print(d)
print("Mean =", d.mean())

# 5. 10x10 random array with min and max
e = np.random.random((10, 10))
print(e)
print("Minimum =", e.min())
print("Maximum =", e.max())

# 6. Zero array and replace 5th element
f = np.zeros(10)
f[4] = 1
print(f)

# 7. Reverse array
arr = [1, 2, 0, 0, 4, 0]

g = np.array(arr)
print(g[::-1])

# 8. 2D array with border 1 and inside 0
h = np.ones((5, 5))
h[1:-1, 1:-1] = 0
print(h)

# 9. Checkerboard pattern
i = np.zeros((8, 8), dtype=int)

i[1::2, ::2] = 1
i[::2, 1::2] = 1

print(i)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.11159254 0.33103783 0.04766356 0.73764647 0.53069036 0.0535541
 0.67794208 0.32912232 0.94779786 0.91630887 0.00333878 0.94680812
 0.14731868 0.80627873 0.33744649 0.65523349 0.9062802  0.19651466
 0.67306151 0.93490628 0.20225858 0.7432792  0.25481488 0.73039451
 0.57809992 0.48790027 0.72157901 0.95071992 0.69641616 0.34059255]
Mean = 0.5332199310919042
[[0.24609149 0.482357   0.90215514 0.32483825 0.984266   0.04977101
  0.51486165 0.57620986 0.49632454 0.43035998]
 [0.66253754 0.55879543 0.64332799 0.79683154 0.20825519 0.71399377
  0.05208565 0.92157724 0.481031   0.48148496]
 [0.99413343 0.22055733 0.64044078 0.66998752 0.93957126 0.90201483
  0.69110181 0.59182327 0.67651447 0.26996095]
 [0.82837471 0.07130439 0.76635911 0.64531664 0.87959441 0.33044465
  0.72898454 0.99379128 0.20490822 0.2

#### Problem 3 Array Operation 

In [21]:
# defining the arrays we will use in all operations below
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print('x =', x)
print('y =', y)
print('v =', v)
print('w =', w)

x = [[1 2]
 [3 5]]
y = [[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]


In [22]:
# 1. adding the two arrays (x + y)

print('1. x + y =')
print(x + y)

1. x + y =
[[ 6  8]
 [10 13]]


In [23]:
# 2. subtract the two arrays (x - y)
print('2. x - y =')
print(x - y)

2. x - y =
[[-4 -4]
 [-4 -3]]


In [24]:
# 3. multiply array by an integer
# Every element gets multiplied by that number
print('3. x multiplied by 3:')
print(x * 3)

3. x multiplied by 3:
[[ 3  6]
 [ 9 15]]


In [25]:
# 4. square of each element
# ** 2 means 'raise to the power of 2' (square)
print('4. Square of each element in x:')
print(x ** 2)

4. Square of each element in x:
[[ 1  4]
 [ 9 25]]


In [26]:
# 5. dot product (this multiplies and sums elements in a specific mathematical way)
print('5a. Dot product of v and w:', np.dot(v, w))

print('5b. Dot product of x and v:')
print(np.dot(x, v))

print('5c. Dot product of x and y:')
print(np.dot(x, y))

5a. Dot product of v and w: 219
5b. Dot product of x and v:
[29 77]
5c. Dot product of x and y:
[[19 22]
 [50 58]]


In [27]:
# 6. Concatenate arrays
# np.vstack() stacks arrays vertically (adds new rows)
# np.hstack() stacks arrays horizontally (adds new columns)

# Concatenate x and y along rows (stack one on top of the other)
concat_rows = np.vstack((x, y))
print('6a. x and y stacked along rows (vstack):')
print(concat_rows)

# Concatenate v and w - they are 1D so hstack puts them side by side
concat_cols = np.hstack((v, w))
print('6b. v and w stacked along column (hstack):')
print(concat_cols)

6a. x and y stacked along rows (vstack):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
6b. v and w stacked along column (hstack):
[ 9 10 11 12]


In [28]:
# 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?


try:
    result = np.vstack((x, v))
    print(result)
except ValueError as e:
    print('ERROR:', e)
    print()
    print('Explanation: x has shape', x.shape, 'and v has shape', v.shape)
    print('vstack needs all arrays to have the same number of columns.')
    print('x has 2 columns but v is 1D, so NumPy does not know how to stack them.')

[[ 1  2]
 [ 3  5]
 [ 9 10]]


#### Problem 4 Matrix Operation

In [29]:
import numpy as np

# Given matrices
A = np.array([[3, 4],
              [7, 8]])

B = np.array([[5, 3],
              [2, 1]])

# 1. Prove A * A^-1 = I

A_inv = np.linalg.inv(A)

print("A inverse:")
print(A_inv)

print("A * A^-1:")
print(np.dot(A, A_inv))


# 2. Prove AB != BA

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:")
print(AB)

print("BA:")
print(BA)


# 3. Prove (AB)^T = B^T A^T

left_side = (AB).T

right_side = np.dot(B.T, A.T)

print("(AB)^T:")
print(left_side)

print("B^T A^T:")
print(right_side)

A inverse:
[[-2.    1.  ]
 [ 1.75 -0.75]]
A * A^-1:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
(AB)^T:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]


#### Solving Linear equation using inverse method 

In [30]:
import numpy as np

# Matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Matrix B
B = np.array([[-1],
              [-3],
              [9]])

# Find inverse of A
A_inv = np.linalg.inv(A)

# Solve X = A^-1 * B
X = np.dot(A_inv, B)

print("Solution:")
print(X)

Solution:
[[ 2.]
 [ 1.]
 [-2.]]


#### Solve Using np.linalg.inv()

In [31]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([[-1],
              [-3],
              [9]])

# Using np.linalg.inv()
X = np.linalg.inv(A).dot(B)

print("Values of x, y, z:")
print(X)

Values of x, y, z:
[[ 2.]
 [ 1.]
 [-2.]]


### 9.2 Experiment: How fast is numpy?

#### Objective:

To compare the performance (speed) of Python Lists and NumPy Arrays for different operations such as:

-Element-wise Addition

-Element-wise Multiplication

-Dot Product

-Matrix Multiplication

In [33]:
# Element wise addition 
import time

n = 1_000_000

a = list(range(n))
b = list(range(n))

start = time.time()

result = []
for i in range(n):
    result.append(a[i] + b[i])

end = time.time()

print("List Addition Time:", end - start)

import numpy as np
import time

n = 1_000_000

a = np.arange(n)
b = np.arange(n)

start = time.time()

result = a + b

end = time.time()

print("NumPy Addition Time:", end - start)

List Addition Time: 0.22905206680297852
NumPy Addition Time: 0.017409324645996094


In [34]:
# Element wise multiplication
import time

n = 1_000_000

a = list(range(n))
b = list(range(n))

start = time.time()

result = []
for i in range(n):
    result.append(a[i] * b[i])

end = time.time()

print("List Multiplication Time:", end - start)

import numpy as np
import time

n = 1_000_000

a = np.arange(n)
b = np.arange(n)

start = time.time()

result = a * b

end = time.time()

print("NumPy Multiplication Time:", end - start)

List Multiplication Time: 0.22507166862487793
NumPy Multiplication Time: 0.021277904510498047


In [35]:
# Dot product 
import time

n = 1_000_000

a = list(range(n))
b = list(range(n))

start = time.time()

dot = 0
for i in range(n):
    dot += a[i] * b[i]

end = time.time()

print("List Dot Product Time:", end - start)

import numpy as np
import time

n = 1_000_000

a = np.arange(n)
b = np.arange(n)

start = time.time()

dot = np.dot(a, b)

end = time.time()

print("NumPy Dot Product Time:", end - start)

List Dot Product Time: 0.33489012718200684
NumPy Dot Product Time: 0.0076045989990234375


In [36]:
# Multiplication matrix 
import time

size = 1000

A = [[1 for _ in range(size)] for _ in range(size)]
B = [[1 for _ in range(size)] for _ in range(size)]

start = time.time()

result = []
for i in range(size):
    row = []
    for j in range(size):
        s = 0
        for k in range(size):
            s += A[i][k] * B[k][j]
        row.append(s)
    result.append(row)

end = time.time()

print("List Matrix Multiplication Time:", end - start)

import numpy as np
import time

size = 1000

A = np.ones((size, size))
B = np.ones((size, size))

start = time.time()

result = np.dot(A, B)

end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)

List Matrix Multiplication Time: 291.88996052742004
NumPy Matrix Multiplication Time: 0.08909392356872559
